apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv-storage
  labels:
    app: jaeger
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/jaeger"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pv-claim
  labels:
    app: jaeger
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1 # important
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      os:
        name: linux
      nodeSelector:
        kubernetes.io/os: linux
      nodeName: minikube
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 10001
      volumes:
        - name: jaeger-pv-storage
          persistentVolumeClaim:
            claimName: jaeger-pv-claim
      containers:
        - name: jaeger
          image: docker.io/jaegertracing/all-in-one:1.67.0
          ports:
            - containerPort: 16686
            - containerPort: 14268
            - containerPort: 4318
          volumeMounts:
            - mountPath: /jaeger
              name: jaeger-pv-storage
          env:
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_EPHEMERAL
              value: "false"
            - name: BADGER_DIRECTORY_VALUE
              value: /jaeger/data
            - name: BADGER_DIRECTORY_KEY
              value: /jaeger/key
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      targetPort: 16686
      port: 16686
      nodePort: 32686
      name: jaeger-ui
    - protocol: TCP
      targetPort: 14268
      port: 14268
      nodePort: 32268
      name: jaeger-thrift
    - protocol: TCP
      targetPort: 4318
      port: 4318
      nodePort: 32318
      name: jaeger-otel
  type: NodePort

